[project]
name = "iv-surface-reconstruction"
version = "0.1.0"
description = ""
authors = [
    {name = "harshilg0yal",email = "harshilgoyal17@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "iv_surface_reconstruction", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
